### ISSUE TITLE
Add method for the components to skip constraints generation

### ISSUE THREAD

**Issue by nkaskov** [NilFoundation/zkllvm-blueprint#308]
For some cases, we only need the result of the component, but not its constraints or assignment rows.

We need to have a way to get the result of component's evaluation but without **any** constraints or rows apart from the rows for the output variables.

**Suggested solution:**
- create an additional `generate_assignments` function (preferably - with the same name, as a template specialization of the original one), which has the same interface as the original one but does not generate any assignment row. It must only generate and seed the result variables with the correct value.
- the same has to be done for `generate_gates`, `generate_copy_constraints` and any other interface-function. By interface functions, I assume functions, which exist for every component and are being used by the user. We do not need to do that work for internally-used functions.
- patch the `result_type` structure so it would also depend on a (preferably - template) parameter. This structure currently returns a link to a cell in the table, and if we skip rows - this link becomes incorrect.

**Comment by akokoshn** [comment]
We can add `skip` parameter for current functions `generate_assignments`, `generate_gates`, `generate_copy_constraints` with default value `FALSE`.
```
generate_assignments(..., skip = false) {
    if (skip) {
        return empty_generate_assignments(...);
    }
    ...
}
```
