### ISSUE TITLE
Substitute component-oriented selectors with gate-oriented

### ISSUE THREAD

**Issue by nkaskov** [NilFoundation/zkllvm-blueprint#60]
Component-oriented selector choice is incorrect and may lead to potential efficiency issues, since we can not distinguish two instances of one component with different input params (parametrized with different input variables) - such instances will have same selectors. And if we directly use variables from params instead of using copy constraints (it may take place in small components, for example), it will lead to undefined behaviour - constraints are different, but selectors are the same.

Most obvious way to fix this is to switch to gate-oriented selectors. But it doesn't sound like an easy task, since it will require building gate ID based on it's content. Most likely we will do it after implementing stable math expression type: https://github.com/NilFoundation/crypto3-math/issues/5 . 

**Until we closed this issue - we always must use copy constraints for params variables!**

**Comment by Iluvmagick** [comment]
Done, switched to gate-based ids for both ordinary and lookup gates.
