### ISSUE TITLE
Dsiable non-working tests

### ISSUE THREAD

**Issue by nkaskov** [NilFoundation/zkllvm-blueprint#83]

**Comment by kotelifelif** [comment]
basic_components

**Comment by kotelifelif** [comment]
basic_components - build
basic_components_r1cs_gg_ppzksnark - build
merkle_tree_components - build

**Comment by kotelifelif** [comment]
Что-то пока здесь ничего не собирается. Пока здесь пропущу.

**Comment by kotelifelif** [comment]
Build:
blueprint_algebra_curves_plonk_fixed_base_scalar_mul_test
blueprint_algebra_curves_r1cs_fixed_base_mul_zcash_test
blueprint_algebra_curves_r1cs_montgomery_test
blueprint_algebra_curves_r1cs_twisted_edwards_test
blueprint_algebra_fields_r1cs_fp2_verification_test
blueprint_algebra_fields_r1cs_fp3_test
blueprint_algebra_fields_r1cs_fp3_verification_test
blueprint_algebra_fields_r1cs_fp4_test
blueprint_algebra_fields_r1cs_fp4_verification_test
blueprint_algebra_fields_r1cs_fp6_2over3_test
blueprint_algebra_fields_r1cs_fp6_2over3_verification_test
blueprint_algebra_pairing_weierstrass_miller_loop_test
blueprint_algebra_pairing_weierstrass_precomputation_test
blueprint_basic_components_r1cs_gg_ppzksnark_test
blueprint_basic_components_test
blueprint_blueprint_plonk_test
blueprint_hashes_plonk_sha256_test
blueprint_hashes_r1cs_knapsack_test
blueprint_hashes_r1cs_knapsack_verification_test
blueprint_hashes_r1cs_pedersen_test
blueprint_hashes_r1cs_sha256_test
blueprint_hashes_r1cs_sha256_verification_test
blueprint_merkle_tree_components_test
blueprint_merkle_tree_plonk_merkle_tree_test
blueprint_non_native_plonk_non_native_demo_test
blueprint_routing_algorithms_routing_algorithms_test
blueprint_routing_as_waksman_test
blueprint_routing_benes_test
blueprint_set_commitment_component_test
blueprint_verifiers_kimchi_basic_verifier_test
blueprint_verifiers_kimchi_batch_verify_scalar_field_test
blueprint_verifiers_kimchi_demo_verifier_test
blueprint_verifiers_kimchi_detail_combine_proof_evals_test
blueprint_verifiers_kimchi_detail_ft_eval_test
blueprint_verifiers_kimchi_oracles_scalar_test
blueprint_verifiers_kimchi_prepare_batch_scalar_test
blueprint_verifiers_kimchi_verify_scalar_test
blueprint_verifiers_r1cs_ppzksnark_test
blueprint_voting_encrypted_input_voting_test

**Comment by kotelifelif** [comment]
Run:
blueprint_algebra_curves_plonk_decomposed_variable_base_scalar_mul_test
blueprint_algebra_curves_plonk_endo_scalar_test
blueprint_algebra_curves_plonk_multi_scalar_multiplication_test
blueprint_algebra_curves_plonk_unified_addition_test
blueprint_algebra_curves_plonk_variable_base_endo_scalar_mul_test
blueprint_algebra_curves_plonk_variable_base_scalar_mul_test
blueprint_algebra_fields_plonk_combined_inner_product_test
blueprint_algebra_fields_plonk_element_powers_test
blueprint_algebra_fields_plonk_exponentiation_test
blueprint_algebra_fields_plonk_field_operations_test
blueprint_algebra_fields_plonk_range_check_test
blueprint_algebra_fields_plonk_sqrt_test
blueprint_hashes_plonk_decomposition_test
blueprint_hashes_plonk_poseidon_test
blueprint_hashes_plonk_sha256_process_test
blueprint_hashes_plonk_sha512_process_test
blueprint_hashes_plonk_sha512_test
blueprint_non_native_plonk_complete_addition_test
blueprint_non_native_plonk_doubling_test
blueprint_non_native_plonk_ec_point_test
blueprint_non_native_plonk_ed25519_test
blueprint_non_native_plonk_field_add_test
blueprint_non_native_plonk_field_mul_test
blueprint_non_native_plonk_field_sub_test
blueprint_non_native_plonk_fixed_base_mul_test
blueprint_non_native_plonk_non_native_range_test
blueprint_non_native_plonk_reduction_test
blueprint_non_native_plonk_signatures_verification_test
blueprint_non_native_plonk_var_base_mul_per_bit_test
blueprint_non_native_plonk_variable_base_multiplication_test
blueprint_verifiers_kimchi_base_field_test
blueprint_verifiers_kimchi_batch_verify_base_field_test
blueprint_verifiers_kimchi_detail__constraints_index_terms_scalars_test
blueprint_verifiers_kimchi_detail_b_poly_coefficients_test
blueprint_verifiers_kimchi_detail_b_poly_test
blueprint_verifiers_kimchi_detail_constraints_generic_scalars_test
blueprint_verifiers_kimchi_detail_constraints_perm_scalars_test
blueprint_verifiers_kimchi_detail_constraints_rpn_expression_test
blueprint_verifiers_kimchi_detail_constraints_unnormalized_lagrange_basis_test
blueprint_verifiers_kimchi_detail_constraints_vanishes_on_last_4_rows_test
blueprint_verifiers_kimchi_detail_lagrange_denominators_test
blueprint_verifiers_kimchi_detail_oracles_cip_test
blueprint_verifiers_kimchi_detail_prepare_scalars_test
blueprint_verifiers_kimchi_detail_prev_chal_evals_test
blueprint_verifiers_kimchi_detail_public_evaluations_test
blueprint_verifiers_kimchi_detail_to_group_test
blueprint_verifiers_kimchi_detail_zk_w3_test
blueprint_verifiers_kimchi_detail_zkpm_evaluate_test
blueprint_verifiers_kimchi_sponge_compare_test
blueprint_verifiers_kimchi_sponge_oracles_test
blueprint_verifiers_kimchi_sponge_sponge_test
blueprint_verifiers_kimchi_sponge_transcript_fq_test
blueprint_verifiers_kimchi_sponge_transcript_fr_test
blueprint_verifiers_kimchi_table_commitment_test
blueprint_verifiers_pickles_verify_heterogenous_base_test
blueprint_verifiers_pickles_verify_heterogenous_scalar_test
