### ISSUE TITLE
Update PLONK components to be compatible with zkllvm assigner interface 

### ISSUE THREAD

**Issue by nkaskov** [NilFoundation/zkllvm-blueprint#90]
zkLLVM assigner requires components to have updated flexible interface, allowing advanced optimizations. Such updates need to be applied to all needed PLONK components.

This is the list of components to start with:

- non-native:
- - bit-decomposition +
- - bool_scalar_multiplication
- - complete_addition_edwards25519
- - doubling_edwards25519
- - ec_point_edwards25519
- - fixed_base_multiplication_edwards25519
- - reduction +
- - scalar_non_native_range
- - variable_base_multiplication_edwards25519
- - variable_base_multiplication_per_bit_edwards25519
- signatures_verification
- ed25519
- sha512

**Comment by tshchelovek** [comment]
680ebe241706ffc18534884471f4231301bf17d5
reduction component+test interface update
