### ISSUE TITLE
Correct scalar recovering in variable base scalar multiplication

### ISSUE THREAD

**Issue by Luannet** [NilFoundation/zkllvm-blueprint#97]
The native field of PlonK is _F_p_ (~ 255 bits) and the non_native is _F_q_ (~255 bits). Determine how to avoid malicious behavior, when scalar bits are recovered into value from _F_q_  in both cases: p < q and q > p. 
The algorithm - https://github.com/NilFoundation/mina-state-proof/blob/master/docs/design/main.pdf (p. 7)

**Comment by Shatooon** [comment]
Let

1) $F_p$ - base field, $F_q$ - scalar field,  $~p=2^{254}+t_p$,  $~q=2^{254}+t_q$,  $~t_p + t_q < 2^{130}$
2) $k = (k_{n-1}, \dots, k_0),~ n=255$
3) $z_i = k_i \cdot 2^i + \dots k_0 \cdot 2^0 $
3) during Scalar Multiplication we recover value $n' = z_{n-1}$

**Case №1: $q < p$** 

- if $z_{n-1} < p$ then $n'$ fits in $F_p$ and all checks are correct
- $z_{n-1} \geq p$ can be used for malicious behavior, because $[z_{n-1}]T \neq [z_{n-1} \mod p]T$
We can use following constraints to avoid this situation
$$z_{n-1} < p \iff k_{254}=0 \lor (k_{254}=1 \land z_{n-2} < t_p) \iff$$
$$k_{254} = 0 \lor \left( k_{254}=1 \land z_{n-2} \in [0;2^{130}) \land z_{n-2}-t_p+2^{130} \in [0;2^{130}) \right)$$

**Case №2: $q > p$**
$n' = z_{n-1}$ doesn't fit in $F_p$ so it should be decomposed: $n' = ~(n_0,n_1) = ~(k_{n-1},z_{n-2}) \in F_{2} \times F_p$
and additional checks for $z_{n-1} \in F_q:$

$$n_0 = k_{254} \land n_1=z_{n-2} \land \left( k_{254} = 0 \lor \left( k_{254}=1 \land z_{n-2} \in [0;2^{130}) \land z_{n-2}-t_q+2^{130} \in [0;2^{130}) \right)\right)$$

**Comment by Shatooon** [comment]
**About Incomplete Addition formulas**

```
P = [2]T
for i from n-1 to 0:
    Q := k_{i+1} ? T : −T
    P := (P + Q) + P
}
```
This algorithm returns $[v]T$, where $v = 2^n+k$, if $k$ is odd, and $v=2^n+k+1$, if $k$ is even. 

It is safe to use incomplete addition formulas only for points $R, S$ such that $x_R \neq x_S$. It is known (see https://eprint.iacr.org/2019/1021.pdf) that $x_R \neq x_S$ if $R=[r]T, ~S=[s]T, -q/2 \leq r,s \leq q/2$ and $|r| \neq |s|$. 

Then we can safely use incomplete addition as long as $u < q/2$, where $P=[u]T$. After $N$ iterations of Variable Base Scalar Multiplication algorithm we have $u \leq 2^{N+1}-1$. For Vesta and Pallas we have:
$$\Rightarrow N \leq 253$$

In this case, it looks like the last 2 iterations should be considered separately using complete addition formulas.

**Comment by Shatooon** [comment]
**Update on Incomplete Addition formulas**

let $k = (k_{n-1}, \dots, k_0),~ n=255$
**variable_base_scalar_mul_test** component calculates VBSM( k ):

```
Q = [2]T    // scalar = 2
for i from n-1 to 0:
    S := k[i] ? T : −T
    Q := (Q + S) + Q    // scalar = 2 * scalar +/- 1
```

$\Rightarrow$ VBSM(k) $= [2^{n+1} + k - (2^n-1-k)]T = [2^n + 2k + 1]T$

Let VBSM(k)\_L calculates only L iterations of VBSM(k):

$\Rightarrow$ VBSM(k, L) $= [2^L + 2k_L + 1]T$  where $~k_L = (k_{n-1}, \dots, k_{n-L})$
Note that VBSM(k,L) $\leq 2^L + 2\cdot(2^{L}-1)+1 = 2^{L+1} + 2^L -1$

For the correctness of incomplete addition in the loop, we must ensure that
1) $Q \neq \mathcal{O} ~ \equiv~ scalar \neq 0$
1) $Q \neq \pm S ~ \equiv~ Q \neq  \pm T  ~ \equiv~ scalar \neq \pm 1$
1) $(Q+S) \neq \mathcal{O} ~ \equiv~ Q \neq -S ~ \equiv~ Q \neq \pm T ~ \equiv~ scalar \neq \pm 1$
1) $(Q+S) \neq Q ~ \equiv~ T \neq \mathcal{O}$
1) $(Q+S) \neq -Q ~ \equiv~ 2Q \neq \pm T ~ \equiv~ scalar \neq \pm 1/2$

We are looking for pairs $(k, L)$: 
 1) VBSM(k,L) $\mod q ~\in ~\\{-1,0,1,1/2, -1/2\\}$
 2) $k \in F_q$, i.e. $(k_L << (255-L)) < q$
 3) $L \leq 255$

**Vesta curve $\\#E(F_p)=q$**
- $L \leq 251~$: assuming that $S \neq 0$ we have $\forall k:~$ VBSM(k,L) < $(q-1)/2 ~\Rightarrow$ there is no solution
- $L = 252$:
$2^L + 2k + 1 < (q-1)/2$ 
$8k$ must be less than $q ~ \Rightarrow 2^{252} + q/4 + 1 < (q-1)/2$
$2^{254} < q -6~$ $~\Rightarrow$ there is no solution
- $253 \leq L \leq 255$:

$k=0x224698fc094cf91b992d30ed00000000, L=253$ (analisys: 1/2 $\Rightarrow k_1$ must be 0, $k_0$ - any)
$k=0x200000000000000000000000000000003369e57a0df375a965c3c96380000000, L=254$ (analisys: -1/2 $\Rightarrow k_0$ must be 1)
$k=0x224698fc094cf91b992d30ed00000000, L=254$
$k=0x224698fc094cf91b992d30ed00000000, L=255$ ($scalar = -1$)
$k=0x300000000000000000000000000000003bfb8bb91046b3f04c0f159ec0000001, L=255$ ($scalar = -1/2$, but we don't have next bit)
$k=0x200000000000000000000000000000003369e57a0df375a965c3c96380000001, L=255$ ($scalar = 0$)
$k=0x100000000000000000000000000000002ad83f3b0ba037627f787d2840000001, L=255$ ($scalar = 1/2$, but we don't have next bit)
$k=0x224698fc094cf91b992d30ed00000001, L=255$ ($scalar = 1$)

Therefore, we have the following exceptional cases
$k = 0x224698fc094cf91b992d30ed00000000$
$k = 0x200000000000000000000000000000003369e57a0df375a965c3c96380000001$
$k = 0x224698fc094cf91b992d30ed00000001$

**Pallas curve $\\#E(F_p)=q$**
- $L \leq 251~$: assuming that $S \neq 0$ we have $\forall k:~$ VBSM(k,L) < $(q-1)/2 ~\Rightarrow$ there is no solution
- $L = 252$:
$2^L + 2k + 1 < (q-1)/2$ 
$8k$ must be less than $q ~ \Rightarrow 2^{252} + q/4 + 1 < (q-1)/2$
$2^{254} < q -6~$ $~\Rightarrow$ there is no solution
- $253 \leq L \leq 255$:

$k=0x224698fc0994a8dd8c46eb2100000000, L=253$ (analisys: 1/2 $\Rightarrow k_1$ must be 0, $k_0$ - any)
$k=0x200000000000000000000000000000003369e57a0e5efd4c526a60b180000000, L=254$ (analisys: -1/2 $\Rightarrow k_0$ must be 1)
$k=0x224698fc0994a8dd8c46eb2100000000, L=254$ ($scalar = 0$)
$k=0x224698fc0994a8dd8c46eb2100000000, L=255$ ($scalar = -1$)
$k=0x300000000000000000000000000000003bfb8bb910c42783b57c1b79c0000001, L=255$ ($scalar = -1/2$, but we don't have next bit)
$k=0x200000000000000000000000000000003369e57a0e5efd4c526a60b180000001, L=255$ ($scalar = 0$)
$k=0x100000000000000000000000000000002ad83f3b0bf9d314ef58a5e940000001, L=255$ ($scalar = 1/2$, but we don't have next bit)
$k=0x224698fc0994a8dd8c46eb2100000001, L=255$ ($scalar = 1$)

Therefore, we have the following exceptional cases
$k=0x224698fc0994a8dd8c46eb2100000000$
$k=0x200000000000000000000000000000003369e57a0e5efd4c526a60b180000001$
$k=0x224698fc0994a8dd8c46eb2100000001$

**Conclusion**. For the case of Vesta and Pallas curves, one of two implementation methods can be chosen.
- Complete Addition for the last four bits $k_2, k_1, k_0$.
- Processing of 3 exceptional scalars.

**Comment by Shatooon** [comment]
*Update on constraint №3*

The set of constraints
- $$z_{n-2} -t_q+2^{130} = \sum_{i=0}^{42}m_i\cdot 2^{127-i \cdot 3} + m_{43}$$
- $m_i(m_i-1)(m_i-2)(m_i-3)(m_i-4)(m_i-5)(m_i-6)(m_i-7), ~i=0, \dots, 42$
- $m_{43}(m_{43}-1)$

is equivalent to the following set:
- $$z_{n-2} -t_q+2^{130} = \sum_{i=0}^{42}m_i\cdot 2^{127-i \cdot 3} + m_{43}$$
- $m_i(m_i-1)(m_i-2)(m_i-3)(m_i-4)(m_i-5)(m_i-6)(m_i-7), ~i=0, \dots, 43$
